# Publsh all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# Position controllers
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: hip_abduction_1
  pid: {p: 100.0, i: 0.0, d: 10.0}