astro:
  controller:
    state:
      # Publish all joint states -----------------------------------
      joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50  

    position:
      # Position Controllers ---------------------------------------
      joint1_position_controller:
        type: position_controllers/JointPositionController
        joint: hip_abduction_1
        pid: {p: 100.0, i: 0.01, d: 10.0}
      joint2_position_controller:
        type: position_controllers/JointPositionController
        joint: hip_flexion_2
        pid: {p: 100.0, i: 0.01, d: 10.0}
      joint3_position_controller:
        type: position_controllers/JointPositionController
        joint: knee_3
        pid: {p: 100.0, i: 0.01, d: 10.0}
