astro:
  hardware_interface:
    joints:
      - hip_0
      - shoulder_0
      - knee_0
      - hip_1
      - shoulder_1
      - knee_1
      - hip_2
      - shoulder_2
      - knee_2
      - hip_3
      - shoulder_3
      - knee_3
    sim_control_mode: 0 # 0: position, 1: velocity

  # Publsh all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Individual Position Controllers ---------------------------------------
  # Allows to send individual ROS msg of Float64 to each joint separately
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: hip_0
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_0
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_0
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: hip_1
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_1
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_1
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: hip_2
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_2
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_2
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint10_position_controller:
    type: effort_controllers/JointPositionController
    joint: hip_3
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_3
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_3
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  # Group Position Controllers ---------------------------------------
  # Allows to send single ROS msg of Float64MultiArray to all joints
  joint_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - hip_0
      - shoulder_0
      - knee_0
      - hip_1
      - shoulder_1
      - knee_1
      - hip_2
      - shoulder_2
      - knee_2
      - hip_3
      - shoulder_3
      - knee_3
    hip_0: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    shoulder_0: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    knee_0: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    hip_1: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    shoulder_1: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    knee_1: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    hip_2: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    shoulder_2: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    knee_2: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    hip_3: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    shoulder_3: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    knee_3: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
