astro:
  hardware_interface:
    joints:
      - hip_abduction_1
      - hip_flexion_2
      - knee_3
      - hip_abduction_4
      - hip_flexion_5
      - knee_6
      - hip_abduction_7
      - hip_flexion_8
      - knee_9
      - hip_abduction_10
      - hip_flexion_11
      - knee_12
    sim_control_mode: 0 # 0: position, 1: velocity

  # Publsh all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Individual Position Controllers ---------------------------------------
  # Allows to send individual ROS msg of Float64 to each joint separately
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: hip_abduction_1
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: hip_flexion_2
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_3
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: hip_abduction_4
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: hip_flexion_5
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_6
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: hip_abduction_7
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: hip_flexion_8
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_9
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint10_position_controller:
    type: effort_controllers/JointPositionController
    joint: hip_abduction_10
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: hip_flexion_11
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee_12
    pid: {p: 1000.0, i: 0.1, d: 10.0}

  # Group Position Controllers ---------------------------------------
  # Allows to send single ROS msg of Float64MultiArray to all joints
  joint_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - hip_abduction_1
      - hip_flexion_2
      - knee_3
      - hip_abduction_4
      - hip_flexion_5
      - knee_6
      - hip_abduction_7
      - hip_flexion_8
      - knee_9
      - hip_abduction_10
      - hip_flexion_11
      - knee_12
    hip_abduction_1: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    hip_flexion_2: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    knee_3: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    hip_abduction_4: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    hip_flexion_5: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    knee_6: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    hip_abduction_7: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    hip_flexion_8: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    knee_9: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    hip_abduction_10: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    hip_flexion_11: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
    knee_12: 
      pid: {p: 1000.0, i: 0.1, d: 10.0}
